[package]
name = "audio-tag-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
mp3-metadata = "0.3.4"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
symphonia = "0.5.4"
